name: Run pytest on push

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to your Python version
      
    - name: Install dependencies
      run: pip install -r starter/requirements.txt

    - name: Run model tests
      run: |
        cd starter/unit_tests
        pytest test.py

    - name: Run api tests
      run: |
        cd starter/unit_tests
        pytest api_tests.py

  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to your Python version
        
    - name: Change directory
      run: cd starter/

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK }}
