name: Deploy to Render

on:
  workflow_run:
    workflows: ["Run pytest on push", "Flake8 Check"]
    types:
      - completed

jobs:
  check_completion:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    outputs:
      both_completed: ${{ github.event.workflow_run.name == 'Run pytest on push' && contains(github.event.workflow_run.name, 'Flake8 Check') }}

    steps:
      - name: Set both_completed flag
        run: echo "both_completed=true" >> $GITHUB_ENV
        if: success()

  deploy:
    needs: check_completion
    runs-on: ubuntu-latest

    if: needs.check_completion.outputs.both_completed == 'true'

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK }}
