name: Deploy to Render

on:
  workflow_run:
    workflows: ["Run pytest on push" , "Flake8 Check"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main' &&
        contains(github.event.workflow_run.name, 'Run pytest on push') &&
        contains(github.event.workflow_run.name, 'Flake8 Check')

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK }}
