name: Flake8 Check

on:
  push:
    branches:
      - main  # Adjust to your main branch name
jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to your Python version

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8
